### ISSUE TITLE
帮忙添加一个jmusupplicant-for-gpnu.git的openwrt.ipk谢谢

### ISSUE THREAD

**Issue by jhuqin** [AmadeusGhost/jmuSupplicant-OpenWrt-ipk#1]
你好，大神，能否麻烦您 ，编译一个，https://github.com/nature2608/jmusupplicant-for-gpnu.git 这个项目的openwrt.ipk版本，原项目编译老出错，麻烦您了。万分感谢。

**Comment by aiamadeus** [comment]
> 原项目编译老出错

把 [这个项目](https://github.com/openjmu/jmuSupplicant-OpenWrt-ipk) git clone 到 package 下能编译吧？用 OpenWrt 主库或者 sdk 编译都行。

> https://github.com/nature2608/jmusupplicant-for-gpnu 这个项目的openwrt.ipk版本

你把 makefile 的这几行改下就行：
```
PKG_SOURCE_URL:=https://github.com/nature2608/jmusupplicant-for-gpnu.git
PKG_REV:=a9a0b2758aa3b33a0497c990925aabc87b5c7be0
```

**Comment by jhuqin** [comment]
您好，已经可以编译出文件了，还有一个问题，这个PKG_REV:=a9a0b2758aa3b33a0497c990925aabc87b5c7be0值是从那里查到的。

**Comment by aiamadeus** [comment]
> 还有一个问题，这个 PKG_REV 值是从哪里查到的。

git log 的 commit hash，项目主页上的 commit history 那右边的 hash 就是。

**Comment by jhuqin** [comment]
好的。太感谢了。
